### ISSUE TITLE
segmentation fault after 10sec

### ISSUE THREAD

**Issue by TheBluePinguin1** [TheBluePinguin1/Genisys#1]
#### OS and versions

* Genisys:
* PHP:
* Server OS:
* Game version: 

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by Driesboy** [comment]
only on windows

**Comment by caspervanneck** [comment]
@driesboy gebruik je anvil

**Comment by Driesboy** [comment]
ja maar het werkt

Op 12-dec.-2016 19:33 schreef "caspervanneck" <notifications@github.com>:

**Comment by caspervanneck** [comment]
@driesboy client crash  dat is jamer

**Comment by TheBluePinguin1** [comment]
UPDATE TO PHP 7.0.14
